name: Report a Bug
description: Something not working as expected? Create an issue to help us improve.
body:
  # - type: markdown
  #   attributes:
  #     value: ---

  - type: input
    id: app-version
    attributes:
      label: Storage Explorer Version
      description: In which Storage Explorer version was this bug encountered?
      placeholder: 1.19.0
    validations:
      required: true
 
  - type: input
    id: regression
    attributes:
      label: Regression From
      description: Was this working in a previous version? If so, which one?
      placeholder: 1.18.0
 
  - type: dropdown
    id: arch
    attributes:
      label: Architecture
      description: Open the About dialog in Storage Explorer to find this.
      options:
        - i86
        - x64
    validations:
      required: true

  - type: input
    id: build-number
    attributes:
      label: Storage Explorer Build Number
      description: Open the About dialog in Storage Explorer to find this.

  - type: markdown
    attributes:
      value: ---

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - All
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      placeholder: Windows 10; macOS Big Sur; Ubuntu 20.04

  - type: markdown
    attributes:
      value: ---

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Provide a clear, concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: List the minimal steps required to reproduce the bug. Be as clear and concise as you can.
      placeholder: |
        1. Launch Storage Explorer
        2. Expand a blob container node.
    validations:
      required: true

 - type: textarea
    id: expected
    attributes:
      label: Expected Experience
      description: Provide a clear, concise description of what you expected to happen. If applicable, add screenshots to help explain what you expected.

  - type: textarea
    id: actual
    attributes:
      label: Actual Experience
      description: Provide a clear, concise description of what actually happens. If applicable, add screenshots to help explain what happened.
    validations:
      required: true
 
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other details, such as error messages, unusual system configurations, network restrictions, etc.
