name: Report a Bug
description: Something not working as expected? Create an issue to help us improve.
type: "Bug"
body:
  - type: markdown
    attributes:
      value: |
        ## Preflight Checklist

        Before submitting a bug report, please make sure you've done the following:
        
        - [ ] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
        - [ ] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
        - [ ] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).
        
        ---

  - type: input
    id: app-version
    attributes:
      label: Storage Explorer Version
      description: In which Storage Explorer version was this bug encountered?
      placeholder: 1.19.0
    validations:
      required: true
 
  - type: input
    id: regression
    attributes:
      label: Regression From
      description: Was this working in a previous version? If so, which one?
      placeholder: 1.18.0
 
  - type: dropdown
    id: arch
    attributes:
      label: Architecture
      description: Open the About dialog in Storage Explorer to find this.
      options:
        - x64
        - arm64
    validations:
      required: true

  - type: input
    id: build-number
    attributes:
      label: Storage Explorer Build Number
      description: Open the About dialog in Storage Explorer to find this.

  - type: markdown
    attributes:
      value: ---

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - All
        - Windows
        - macOS
        - Linux (tar.gz)
        - Linux (snap)
    validations:
      required: true
      
  - type: input
    id: os-version
    attributes:
      label: OS Version
      placeholder: Windows 11; macOS Sequioa 15.3.1; Ubuntu 22.04

  - type: markdown
    attributes:
      value: ---

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Provide a clear, concise description of the bug.
      placeholder: |
        Describe the bug you're seeing.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: List the minimal steps required to reproduce the bug. Be as clear and concise as you can.
      placeholder: |
        1. Launch Storage Explorer
        2. Expand a blob container node.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Experience
      description: Provide a clear, concise description of what actually happens. If applicable, add screenshots to help explain what happened.
      placeholder: |
        What actually happens when I follow the steps to reproduce?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Experience
      description: Provide a clear, concise description of what you expected to happen. If applicable, add screenshots to help explain what you expected.
      placeholder: |
        What should happen when I follow the steps to reproduce?

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other details, such as error messages, unusual system configurations, network restrictions, etc.
      placeholder: |
        Error messages, proxy configurations, system permissions, etc.
        
